"""Add is_archived field to development_requests

Revision ID: 13d5a76d8221
Revises: 9edc0c222c7e
Create Date: 2026-04-04 14:17:22.809196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13d5a76d8221'
down_revision: Union[str, None] = '9edc0c222c7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('development_requests', sa.Column('is_archived', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_development_requests_is_archived'), 'development_requests', ['is_archived'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_development_requests_is_archived'), table_name='development_requests')
    op.drop_column('development_requests', 'is_archived')
    # ### end Alembic commands ###
