"""Remove unique constraint from job_id

Revision ID: 170d4a40ab57
Revises: 593f0bdc410a
Create Date: 2026-04-04 04:09:41.305317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '170d4a40ab57'
down_revision: Union[str, None] = '593f0bdc410a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sync_records_job_id'), table_name='sync_records')
    op.create_index(op.f('ix_sync_records_job_id'), 'sync_records', ['job_id'], unique=False)
    op.create_index('ix_sync_records_job_module', 'sync_records', ['job_id', 'module_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sync_records_job_module', table_name='sync_records')
    op.drop_index(op.f('ix_sync_records_job_id'), table_name='sync_records')
    op.create_index(op.f('ix_sync_records_job_id'), 'sync_records', ['job_id'], unique=True)
    # ### end Alembic commands ###
