"""Create development request tables

Revision ID: 9edc0c222c7e
Revises: 7b401f30a57e
Create Date: 2026-04-04 10:49:50.714074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9edc0c222c7e'
down_revision: Union[str, None] = '7b401f30a57e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('functional_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_functional_categories_name'), 'functional_categories', ['name'], unique=True)
    op.create_table('priorities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_priorities_name'), 'priorities', ['name'], unique=True)
    op.create_table('request_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_request_states_name'), 'request_states', ['name'], unique=True)
    op.create_table('request_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_request_types_name'), 'request_types', ['name'], unique=True)
    op.create_table('development_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_number', sa.String(length=20), nullable=False),
    sa.Column('request_type_id', sa.Integer(), nullable=False),
    sa.Column('functional_category_id', sa.Integer(), nullable=False),
    sa.Column('request_state_id', sa.Integer(), nullable=False),
    sa.Column('priority_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('uat_request_id', sa.String(length=100), nullable=True),
    sa.Column('assigned_developer_id', sa.Integer(), nullable=True),
    sa.Column('request_date', sa.DateTime(), nullable=False),
    sa.Column('request_close_date', sa.DateTime(), nullable=True),
    sa.Column('parent_request_id', sa.Integer(), nullable=True),
    sa.Column('related_request_id', sa.Integer(), nullable=True),
    sa.Column('iteration_counter', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_developer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['functional_category_id'], ['functional_categories.id'], ),
    sa.ForeignKeyConstraint(['parent_request_id'], ['development_requests.id'], ),
    sa.ForeignKeyConstraint(['priority_id'], ['priorities.id'], ),
    sa.ForeignKeyConstraint(['related_request_id'], ['development_requests.id'], ),
    sa.ForeignKeyConstraint(['request_state_id'], ['request_states.id'], ),
    sa.ForeignKeyConstraint(['request_type_id'], ['request_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_development_requests_request_number'), 'development_requests', ['request_number'], unique=True)
    op.create_table('request_module_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('module_technical_name', sa.String(length=255), nullable=False),
    sa.Column('module_version', sa.String(length=100), nullable=True),
    sa.Column('module_md5_sum', sa.String(length=64), nullable=True),
    sa.Column('email_thread_zip', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['development_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('request_release_plan_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('release_plan_date', sa.DateTime(), nullable=False),
    sa.Column('release_plan_status', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['development_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('request_release_plan_lines')
    op.drop_table('request_module_lines')
    op.drop_index(op.f('ix_development_requests_request_number'), table_name='development_requests')
    op.drop_table('development_requests')
    op.drop_index(op.f('ix_request_types_name'), table_name='request_types')
    op.drop_table('request_types')
    op.drop_index(op.f('ix_request_states_name'), table_name='request_states')
    op.drop_table('request_states')
    op.drop_index(op.f('ix_priorities_name'), table_name='priorities')
    op.drop_table('priorities')
    op.drop_index(op.f('ix_functional_categories_name'), table_name='functional_categories')
    op.drop_table('functional_categories')
    # ### end Alembic commands ###
