"""Create users environments modules sync_records tables

Revision ID: b16a91908429
Revises: c1506b343175
Create Date: 2026-04-04 00:57:16.598538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b16a91908429'
down_revision: Union[str, None] = 'c1506b343175'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('environments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('db_name', sa.String(length=100), nullable=False),
    sa.Column('user', sa.String(length=255), nullable=False),
    sa.Column('encrypted_password', sa.LargeBinary(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_environments_name'), 'environments', ['name'], unique=True)
    op.create_table('modules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('shortdesc', sa.String(length=500), nullable=True),
    sa.Column('first_seen_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_modules_name'), 'modules', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('sync_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('environment_id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=True),
    sa.Column('version_major', sa.Integer(), nullable=True),
    sa.Column('version_minor', sa.Integer(), nullable=True),
    sa.Column('version_patch', sa.Integer(), nullable=True),
    sa.Column('version_build', sa.Integer(), nullable=True),
    sa.Column('version_string', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='syncstatus'), nullable=False),
    sa.Column('progress_percent', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], ),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sync_records_env_module', 'sync_records', ['environment_id', 'module_id'], unique=False)
    op.create_index(op.f('ix_sync_records_environment_id'), 'sync_records', ['environment_id'], unique=False)
    op.create_index(op.f('ix_sync_records_job_id'), 'sync_records', ['job_id'], unique=True)
    op.create_index(op.f('ix_sync_records_status'), 'sync_records', ['status'], unique=False)
    op.create_index('ix_sync_records_version_sort', 'sync_records', ['version_major', 'version_minor', 'version_patch', 'version_build'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sync_records_version_sort', table_name='sync_records')
    op.drop_index(op.f('ix_sync_records_status'), table_name='sync_records')
    op.drop_index(op.f('ix_sync_records_job_id'), table_name='sync_records')
    op.drop_index(op.f('ix_sync_records_environment_id'), table_name='sync_records')
    op.drop_index('ix_sync_records_env_module', table_name='sync_records')
    op.drop_table('sync_records')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_modules_name'), table_name='modules')
    op.drop_table('modules')
    op.drop_index(op.f('ix_environments_name'), table_name='environments')
    op.drop_table('environments')
    # ### end Alembic commands ###
