"""add_dependencies_to_sync_records

Revision ID: b277ce35cd25
Revises: merge_heads
Create Date: 2026-04-05 19:29:29.195400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b277ce35cd25'
down_revision: Union[str, None] = 'merge_heads'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('audit_logs_changed_by_id_fkey'), 'audit_logs', type_='foreignkey')
    op.create_foreign_key(None, 'audit_logs', 'users', ['changed_by_id'], ['id'])
    op.drop_constraint(op.f('fk_dev_requests_updated_by'), 'development_requests', type_='foreignkey')
    op.drop_constraint(op.f('fk_dev_requests_created_by'), 'development_requests', type_='foreignkey')
    op.create_foreign_key(None, 'development_requests', 'users', ['updated_by_id'], ['id'])
    op.create_foreign_key(None, 'development_requests', 'users', ['created_by_id'], ['id'])
    op.alter_column('release_plans', 'source_environment_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('release_plans', 'target_environment_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('request_attachments_uploaded_by_id_fkey'), 'request_attachments', type_='foreignkey')
    op.drop_constraint(op.f('request_attachments_request_id_fkey'), 'request_attachments', type_='foreignkey')
    op.create_foreign_key(None, 'request_attachments', 'users', ['uploaded_by_id'], ['id'])
    op.create_foreign_key(None, 'request_attachments', 'development_requests', ['request_id'], ['id'])
    op.drop_constraint(op.f('request_comments_request_id_fkey'), 'request_comments', type_='foreignkey')
    op.drop_constraint(op.f('request_comments_user_id_fkey'), 'request_comments', type_='foreignkey')
    op.drop_constraint(op.f('request_comments_parent_comment_id_fkey'), 'request_comments', type_='foreignkey')
    op.create_foreign_key(None, 'request_comments', 'request_comments', ['parent_comment_id'], ['id'])
    op.create_foreign_key(None, 'request_comments', 'development_requests', ['request_id'], ['id'])
    op.create_foreign_key(None, 'request_comments', 'users', ['user_id'], ['id'])
    op.add_column('sync_records', sa.Column('dependencies', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sync_records', 'dependencies')
    op.drop_constraint(None, 'request_comments', type_='foreignkey')
    op.drop_constraint(None, 'request_comments', type_='foreignkey')
    op.drop_constraint(None, 'request_comments', type_='foreignkey')
    op.create_foreign_key(op.f('request_comments_parent_comment_id_fkey'), 'request_comments', 'request_comments', ['parent_comment_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('request_comments_user_id_fkey'), 'request_comments', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('request_comments_request_id_fkey'), 'request_comments', 'development_requests', ['request_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'request_attachments', type_='foreignkey')
    op.drop_constraint(None, 'request_attachments', type_='foreignkey')
    op.create_foreign_key(op.f('request_attachments_request_id_fkey'), 'request_attachments', 'development_requests', ['request_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('request_attachments_uploaded_by_id_fkey'), 'request_attachments', 'users', ['uploaded_by_id'], ['id'], ondelete='SET NULL')
    op.alter_column('release_plans', 'target_environment_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('release_plans', 'source_environment_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'development_requests', type_='foreignkey')
    op.drop_constraint(None, 'development_requests', type_='foreignkey')
    op.create_foreign_key(op.f('fk_dev_requests_created_by'), 'development_requests', 'users', ['created_by_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_dev_requests_updated_by'), 'development_requests', 'users', ['updated_by_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.create_foreign_key(op.f('audit_logs_changed_by_id_fkey'), 'audit_logs', 'users', ['changed_by_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
