"""add_mismatch_reason_to_version_drift_entries

Revision ID: bc66b7c1dff6
Revises: d1e2f3a4b5c6
Create Date: 2026-04-09 16:37:25.495399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bc66b7c1dff6'
down_revision: Union[str, None] = 'd1e2f3a4b5c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comparison_report_rows_report_id'), table_name='comparison_report_rows')
    op.create_index(op.f('ix_comparison_report_rows_comparison_report_id'), 'comparison_report_rows', ['comparison_report_id'], unique=False)
    op.alter_column('development_request_state_type_rules', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('development_request_state_type_rules', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_module_dependencies_environment_id'), 'module_dependencies', ['environment_id'], unique=False)
    op.create_index(op.f('ix_module_dependencies_module_id'), 'module_dependencies', ['module_id'], unique=False)
    op.alter_column('refresh_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_saved_views_is_public'), table_name='saved_views')
    op.drop_index(op.f('ix_saved_views_user_id'), table_name='saved_views')
    op.add_column('version_drift_entries', sa.Column('mismatch_reason', sa.String(length=255), nullable=True))
    op.drop_index(op.f('ix_version_drift_entries_report_id'), table_name='version_drift_entries')
    op.create_index(op.f('ix_version_drift_entries_comparison_report_id'), 'version_drift_entries', ['comparison_report_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_version_drift_entries_comparison_report_id'), table_name='version_drift_entries')
    op.create_index(op.f('ix_version_drift_entries_report_id'), 'version_drift_entries', ['comparison_report_id'], unique=False)
    op.drop_column('version_drift_entries', 'mismatch_reason')
    op.create_index(op.f('ix_saved_views_user_id'), 'saved_views', ['user_id'], unique=False)
    op.create_index(op.f('ix_saved_views_is_public'), 'saved_views', ['is_public'], unique=False)
    op.alter_column('refresh_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_module_dependencies_module_id'), table_name='module_dependencies')
    op.drop_index(op.f('ix_module_dependencies_environment_id'), table_name='module_dependencies')
    op.alter_column('development_request_state_type_rules', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('development_request_state_type_rules', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_comparison_report_rows_comparison_report_id'), table_name='comparison_report_rows')
    op.create_index(op.f('ix_comparison_report_rows_report_id'), 'comparison_report_rows', ['comparison_report_id'], unique=False)
    # ### end Alembic commands ###
