"""Add ControlParameterRule model

Revision ID: c1909407f0bf
Revises: 13d5a76d8221
Create Date: 2026-04-04 22:49:27.262108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1909407f0bf'
down_revision: Union[str, None] = '13d5a76d8221'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('control_parameter_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_state_name', sa.String(length=255), nullable=False),
    sa.Column('allowed_type_categories', sa.String(length=255), nullable=False),
    sa.Column('allowed_priorities', sa.String(length=255), nullable=False),
    sa.Column('allowed_functional_categories', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('control_parameter_rules')
    # ### end Alembic commands ###
